require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ListsController do

  # This should return the minimal set of attributes required to create a valid
  # List. As you add validations to List, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :name => "My list", :private => false }
  end

  describe "GET index" do
    it "assigns all lists as @lists" do
      list = List.create! valid_attributes
      get :index
      assigns(:lists).should eq([list])
    end
  end

  describe "GET show" do
    it "assigns the requested list as @list" do
      list = List.create! valid_attributes
      get :show, :id => list.id
      assigns(:list).should eq(list)
    end
  end
  
end
